### PR TITLE
Updated generated code and fixed isses

### LINKED ISSUE #68: Is this Defold extension still active?
Hello,

I am planning to develop a game using  Defiold and Nakama server. Still, I found out the latest release for this extension was in 2022 while other Nakama extensions for other engines (e.g. nakama-js) have several versions in 2023.

Is this defold extension still active and supports all Nakama features?

### PR DESCRIPTION
**Pull request by britzl**
* Updated generated code to the latest API definitions.
* Fixed issues with newlines in API descriptions
* Updated example to match new authentication signature

Fixes #68

### CODE REVIEW

File: codegen/rest.go [hunk 1]
```diff
@@ -225,14 +225,14 @@ end
...
 {{- $varName := $varName | pascalToSnake }}
 {{- $varComment := varComment $parameter.Name $parameter.Type $parameter.Schema.Ref $parameter.Items.Type }}
-{{- if and (eq $parameter.Name "body") $parameter.Schema.Ref }}
+{{- if and (eq $parameter.In "body") $parameter.Schema.Ref }}
 {{- bodyFunctionArgsDocs $parameter.Schema.Ref }}
 {{- end }}
-{{- if and (eq $parameter.Name "body") $parameter.Schema.Type }}
--- @param body ({{ $parameter.Schema.Type }}) {{ $parameter.Description }}
+{{- if and (eq $parameter.In "body") $parameter.Schema.Type }}
+-- @param body ({{ $parameter.Schema.Type }}) {{ $parameter.Description | stripNewlines }}
```
Comment (britzl) [inline codegen/rest.go:232]: Some descriptions have embedded newlines which ends up messing with the generated code

File: codegen/rest.go [hunk 2]
```diff
@@ -225,14 +225,14 @@ end
 {{- $varName := varName $parameter.Name $parameter.Type $parameter.Schema.Ref }}
 {{- $varName := $varName | pascalToSnake }}
 {{- $varComment := varComment $parameter.Name $parameter.Type $parameter.Schema.Ref $parameter.Items.Type }}
-{{- if and (eq $parameter.Name "body") $parameter.Schema.Ref }}
+{{- if and (eq $parameter.In "body") $parameter.Schema.Ref }}
```
Comment (britzl) [inline codegen/rest.go:228]: This change seems to have happened in November 2022. I saw that the other code generators transitioned to the use of "In" instead of "Name".

**Review by tomglenn — APPROVED** [review]

**Comment by tomglenn** [comment]
Awesome, thanks @britzl 🙏

**Comment by britzl** [comment]
@tomglenn can you also make a new release?

**Comment by tomglenn** [comment]
@britzl 3.2.0 release made.
